name: Command Dispatcher
on:
  issue_comment:
    types: [created]
jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commands: help, release-prepare, release-perform, release-clean, release-rollback, qa-demo-2x-bs3-tests, qa-demo-2x-bs4-tests, qa-demo-2x-bs5-tests
        permission: none
        issue-type: both
