name: help-command
on:
  repository_dispatch:
    types: [help-command]
jobs:
  help:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Set Command Reaction
      uses: peter-evans/create-or-update-comment@v2
      with:
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reactions: +1, heart

    - name: Comment for Command
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
            @${{ github.event.client_payload.github.payload.comment.user.login }} Please comment on any issue with:
            - `/qa-demo-2x-bs3-tests` to run QA tests with BS3 theme setup
            - `/qa-demo-2x-bs4-tests` to run QA tests with BS4 theme setup
            - `/qa-demo-2x-bs5-tests` to run QA tests with BS5 theme setup
