# Schema for the configuration files of the Google Map Field module.

google_map_field.settings:
  type: config_object
  label: 'Google Map Field settings'
  mapping:
    google_map_field_auth_method:
      type: integer
      label: 'Google API Authentication Method'
    google_map_field_apikey:
      type: string
      label: 'Google Maps API Key'
    google_map_field_map_client_id:
      type: string
      label: 'Google Maps API for Work: Client ID'
