<?php

/**
 * @file
 * The module file for dxpr_builder_media.
 */

/**
 * Implements hook_preprocess_views_view().
 *
 * @phpstan-param array<string, mixed> $variables
 */
function dxpr_builder_media_preprocess_views_view(array &$variables): void {
  if ($variables['view']->id() === 'dxpr_builder_media') {
    // Get the active theme.
    $active_theme = \Drupal::theme()->getActiveTheme()->getName();

    // Get the base theme of active theme.
    /* @phpstan-ignore-next-line */
    $base_theme = \Drupal::service('theme_handler')->listInfo()[$active_theme]->base_theme;

    // Check if the active theme or base theme is 'gin'.
    if ($active_theme === 'gin' || $base_theme === 'gin') {
      $variables['view_array']['#attached']['library'][] = 'dxpr_builder_media/gin_style';
    }
    else {
      $variables['view_array']['#attached']['library'][] = 'dxpr_builder_media/claro_style';
    }
    $variables['view_array']['#attached']['library'][] = 'dxpr_builder_media/view';
  }
}

/**
 * Implements hook_library_info_alter().
 *
 * @phpstan-param array<string, mixed> $libraries
 */
function dxpr_builder_media_library_info_alter(array &$libraries, string $extension): void {
  if ($extension === 'dxpr_builder_media' && isset($libraries['view'])) {
    /** @var \Drupal\Core\Asset\LibraryDiscoveryInterface $library_discovery */
    $library_discovery = \Drupal::service('library.discovery');

    $core_underscore = $library_discovery->getLibraryByName('core', 'underscore');
    $core_backbone = $library_discovery->getLibraryByName('core', 'backbone');

    $libs = [
      "view",
    ];

    foreach ($libs as $lib) {
      if ($core_underscore) {
        $libraries[$lib]['dependencies'][] = 'core/underscore';
      }
      else {
        $libraries[$lib]['dependencies'][] = 'dxpr_builder/underscore';
      }

      if ($core_backbone) {
        $libraries[$lib]['dependencies'][] = 'core/backbone';
      }
      else {
        // @todo Replace with dxpr_builder/backbone library.
        $libraries[$lib]['dependencies'][] = 'core/internal.backbone';
      }
    }
  }
}
